version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - PORT=8008
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=lms_forum_id
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret_key_here
      - FRONTEND_URL=http://localhost:8008
    restart: unless-stopped